//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outbreak
    {
        public int OutbreakID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<System.DateTime> OutbreakDate { get; set; }
        public string OutbreakCity { get; set; }
        public Nullable<int> NumberOfCasualties { get; set; }
        public string OutbreakDescription { get; set; }
    
        public virtual ActiveArea ActiveArea { get; set; }
    }
}
