//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Symptom
    {
        public int SymptomID { get; set; }
        public Nullable<int> DiseaseID { get; set; }
        public string SymptomName { get; set; }
        public string SymptomDescription { get; set; }
        public string SymptomSeverity { get; set; }
        public string SymptomAppears { get; set; }
        public string DefiningCharacteristic { get; set; }
    
        public virtual Disease Disease { get; set; }
    }
}
