//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int TreatmentID { get; set; }
        public Nullable<int> DiseaseID { get; set; }
        public string TreatmentName { get; set; }
        public string TreatmentDescription { get; set; }
        public string AvailableAt { get; set; }
        public string TreatmentDuration { get; set; }
        public string AfterCare { get; set; }
        public string TreatmentEffective { get; set; }
        public string Aftermath { get; set; }
    
        public virtual Disease Disease { get; set; }
    }
}
